language: c

env:
    - SMVERSION=1.6

matrix:
    fast_finish: true

before_install:
    - sudo apt-get update
    - sudo apt-get install gcc-multilib
    - sudo apt-get install lynx
    - sudo apt-get install lib32stdc++6

before_script:
    - SMPATTERN="http:.*sourcemod-.*-linux.*"
    - SMURL="http://www.sourcemod.net/smdrop/$SMVERSION/"
    - SMPACKAGE=`lynx -dump "$SMURL" | egrep -o "$SMPATTERN" | tail -1`
    - wget $SMPACKAGE
    - tar -xzf $(basename "$SMPACKAGE")
    - cd addons/sourcemod/scripting/
    - chmod +x spcomp
    - chmod +x compile.sh

script: 
    - ./compile.sh

after_script:
    - ls ../plugin